name: Build
on: # rebuild any main branch changes
  push:
    branches:
      - master

jobs:
  build: # make sure build/ci work properly
    name: Build and Test
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    
    steps:
      - name: Get source
        uses: actions/checkout@v1
      - name: Restore Dependencies
        run: npm ci
      - name: Build
        run: npm run all